# Import Libraries

In [1]:
import pandas as pd
import numpy as np

# Load Dataset

In [2]:
df = pd.read_csv('../datasets/dataset.csv')

In [3]:
df.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(4920, 18)

In [5]:
df.columns

Index(['Disease', 'Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4',
       'Symptom_5', 'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9',
       'Symptom_10', 'Symptom_11', 'Symptom_12', 'Symptom_13', 'Symptom_14',
       'Symptom_15', 'Symptom_16', 'Symptom_17'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Disease     4920 non-null   str
 1   Symptom_1   4920 non-null   str
 2   Symptom_2   4920 non-null   str
 3   Symptom_3   4920 non-null   str
 4   Symptom_4   4572 non-null   str
 5   Symptom_5   3714 non-null   str
 6   Symptom_6   2934 non-null   str
 7   Symptom_7   2268 non-null   str
 8   Symptom_8   1944 non-null   str
 9   Symptom_9   1692 non-null   str
 10  Symptom_10  1512 non-null   str
 11  Symptom_11  1194 non-null   str
 12  Symptom_12  744 non-null    str
 13  Symptom_13  504 non-null    str
 14  Symptom_14  306 non-null    str
 15  Symptom_15  240 non-null    str
 16  Symptom_16  192 non-null    str
 17  Symptom_17  72 non-null     str
dtypes: str(18)
memory usage: 692.0 KB

In [7]:
df.describe()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
count,4920,4920,4920,4920,4572,3714,2934,2268,1944,1692,1512,1194,744,504,306,240,192,72
unique,41,34,48,54,50,38,32,26,21,22,21,18,11,8,4,3,3,1
top,Fungal infection,vomiting,vomiting,fatigue,high_fever,headache,nausea,abdominal_pain,abdominal_pain,yellowing_of_eyes,yellowing_of_eyes,irritability,malaise,muscle_pain,chest_pain,chest_pain,blood_in_sputum,muscle_pain
freq,120,822,870,726,378,348,390,264,276,228,198,120,126,72,96,144,72,72

In [8]:
df.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [10]:
df['Disease'].value_counts()

Disease
Fungal infection                           120
Allergy                                    120
GERD                                       120
Chronic cholestasis                        120
Drug Reaction                              120
Peptic ulcer diseae                        120
AIDS                                       120
Diabetes                                   120
Gastroenteritis                            120
Bronchial Asthma                           120
Hypertension                               120
Migraine                                   120
Cervical spondylosis                       120
Paralysis (brain hemorrhage)               120
Jaundice                                   120
Malaria                                    120
Chicken pox                                120
Dengue                                     120
Typhoid                                    120
hepatitis A                                120
Hepatitis B                                120
Hepatitis C                                120
Hepatitis D                                120
Hepatitis E                                120
Alcoholic hepatitis                        120
Tuberculosis                               120
Common Cold                                120
Pneumonia                                  120
Dimorphic hemmorhoids(piles)               120
Heart attack                               120
Varicose veins                             120
Hypothyroidism                             120
Hyperthyroidism                            120
Hypoglycemia                               120
Osteoarthristis                            120
Arthritis                                  120
(vertigo) Paroymsal  Positional Vertigo    120
Acne                                       120
Urinary tract infection                    120
Psoriasis                                  120
Impetigo                                   120
Name: count, dtype: int64

In [11]:
for col in df.columns[1:]:
    df[col] = df[col].str.strip()

In [12]:
symptoms = set()

for col in df.columns[1:]:
    symptoms.update(df[col].dropna().unique())

print(len(symptoms))

131

In [13]:
symptoms

{'abdominal_pain',
 'abnormal_menstruation',
 'acidity',
 'acute_liver_failure',
 'altered_sensorium',
 'anxiety',
 'back_pain',
 'belly_pain',
 'blackheads',
 'bladder_discomfort',
 'blister',
 'blood_in_sputum',
 'bloody_stool',
 'blurred_and_distorted_vision',
 'breathlessness',
 'brittle_nails',
 'bruising',
 'burning_micturition',
 'chest_pain',
 'chills',
 'cold_hands_and_feets',
 'coma',
 'congestion',
 'constipation',
 'continuous_feel_of_urine',
 'continuous_sneezing',
 'cough',
 'cramps',
 'dark_urine',
 'dehydration',
 'depression',
 'diarrhoea',
 'dischromic _patches',
 'distention_of_abdomen',
 'dizziness',
 'drying_and_tingling_lips',
 'enlarged_thyroid',
 'excessive_hunger',
 'extra_marital_contacts',
 'family_history',
 'fast_heart_rate',
 'fatigue',
 'fluid_overload',
 'foul_smell_of urine',
 'headache',
 'high_fever',
 'hip_joint_pain',
 'history_of_alcohol_consumption',
 'increased_appetite',
 'indigestion',
 'inflammatory_nails',
 'internal_itching',
 'irregular_sugar_level',
 'irritability',
 'irritation_in_anus',
 'itching',
 'joint_pain',
 'knee_pain',
 'lack_of_concentration',
 'lethargy',
 'loss_of_appetite',
 'loss_of_balance',
 'loss_of_smell',
 'malaise',
 'mild_fever',
 'mood_swings',
 'movement_stiffness',
 'mucoid_sputum',
 'muscle_pain',
 'muscle_wasting',
 'muscle_weakness',
 'nausea',
 'neck_pain',
 'nodal_skin_eruptions',
 'obesity',
 'pain_behind_the_eyes',
 'pain_during_bowel_movements',
 'pain_in_anal_region',
 'painful_walking',
 'palpitations',
 'passage_of_gases',
 'patches_in_throat',
 'phlegm',
 'polyuria',
 'prominent_veins_on_calf',
 'puffy_face_and_eyes',
 'pus_filled_pimples',
 'receiving_blood_transfusion',
 'receiving_unsterile_injections',
 'red_sore_around_nose',
 'red_spots_over_body',
 'redness_of_eyes',
 'restlessness',
 'runny_nose',
 'rusty_sputum',
 'scurring',
 'shivering',
 'silver_like_dusting',
 'sinus_pressure',
 'skin_peeling',
 'skin_rash',
 'slurred_speech',
 'small_dents_in_nails',
 'spinning_movements',
 'spotting_ urination',
 'stiff_neck',
 'stomach_bleeding',
 'stomach_pain',
 'sunken_eyes',
 'sweating',
 'swelled_lymph_nodes',
 'swelling_joints',
 'swelling_of_stomach',
 'swollen_blood_vessels',
 'swollen_extremeties',
 'swollen_legs',
 'throat_irritation',
 'toxic_look_(typhos)',
 'ulcers_on_tongue',
 'unsteadiness',
 'visual_disturbances',
 'vomiting',
 'watering_from_eyes',
 'weakness_in_limbs',
 'weakness_of_one_body_side',
 'weight_gain',
 'weight_loss',
 'yellow_crust_ooze',
 'yellow_urine',
 'yellowing_of_eyes',
 'yellowish_skin'}

# Disease Distribution

In [ ]:
import matplotlib.pyplot as plt

df['Disease'].value_counts().plot(kind='bar', figsize=(12,5))

plt.title("Disease Distribution")
plt.xlabel("Disease")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.show()

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Disease'] = le.fit_transform(df['Disease'])

In [15]:
disease_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

print(disease_mapping)

{'(vertigo) Paroymsal  Positional Vertigo': np.int64(0), 'AIDS': np.int64(1), 'Acne': np.int64(2), 'Alcoholic hepatitis': np.int64(3), 'Allergy': np.int64(4), 'Arthritis': np.int64(5), 'Bronchial Asthma': np.int64(6), 'Cervical spondylosis': np.int64(7), 'Chicken pox': np.int64(8), 'Chronic cholestasis': np.int64(9), 'Common Cold': np.int64(10), 'Dengue': np.int64(11), 'Diabetes ': np.int64(12), 'Dimorphic hemmorhoids(piles)': np.int64(13), 'Drug Reaction': np.int64(14), 'Fungal infection': np.int64(15), 'GERD': np.int64(16), 'Gastroenteritis': np.int64(17), 'Heart attack': np.int64(18), 'Hepatitis B': np.int64(19), 'Hepatitis C': np.int64(20), 'Hepatitis D': np.int64(21), 'Hepatitis E': np.int64(22), 'Hypertension ': np.int64(23), 'Hyperthyroidism': np.int64(24), 'Hypoglycemia': np.int64(25), 'Hypothyroidism': np.int64(26), 'Impetigo': np.int64(27), 'Jaundice': np.int64(28), 'Malaria': np.int64(29), 'Migraine': np.int64(30), 'Osteoarthristis': np.int64(31), 'Paralysis (brain hemorrhage)': np.int64(32), 'Peptic ulcer diseae': np.int64(33), 'Pneumonia': np.int64(34), 'Psoriasis': np.int64(35), 'Tuberculosis': np.int64(36), 'Typhoid': np.int64(37), 'Urinary tract infection': np.int64(38), 'Varicose veins': np.int64(39), 'hepatitis A': np.int64(40)}

In [16]:
all_symptoms = list(symptoms)

X = pd.DataFrame(0,
                 index=np.arange(len(df)),
                 columns=all_symptoms)

In [17]:
for i in range(len(df)):
    
    row_symptoms = df.iloc[i, 1:].dropna()

    for symptom in row_symptoms:
        X.loc[i, symptom] = 1

# Target Variable

In [18]:
y = df['Disease']

In [19]:
print(X.shape)

(4920, 131)

# Train-Test Split

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Model

In [21]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

# Evaluate

In [22]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print(
    accuracy_score(y_test, pred)
)

1.0

In [23]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)

print(cm)

[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]

In [24]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        30
           2       1.00      1.00      1.00        24
           3       1.00      1.00      1.00        25
           4       1.00      1.00      1.00        24
           5       1.00      1.00      1.00        23
           6       1.00      1.00      1.00        33
           7       1.00      1.00      1.00        23
           8       1.00      1.00      1.00        21
           9       1.00      1.00      1.00        15
          10       1.00      1.00      1.00        23
          11       1.00      1.00      1.00        26
          12       1.00      1.00      1.00        21
          13       1.00      1.00      1.00        29
          14       1.00      1.00      1.00        24
          15       1.00      1.00      1.00        19
          16       1.00      1.00      1.00        28
          17       1.00      1.00      1.00        25
          18       1.00      1.00      1.00        23
          19       1.00      1.00      1.00        27
          20       1.00      1.00      1.00        26
          21       1.00      1.00      1.00        23
          22       1.00      1.00      1.00        29
          23       1.00      1.00      1.00        25
          24       1.00      1.00      1.00        24
          25       1.00      1.00      1.00        26
          26       1.00      1.00      1.00        21
          27       1.00      1.00      1.00        24
          28       1.00      1.00      1.00        19
          29       1.00      1.00      1.00        22
          30       1.00      1.00      1.00        25
          31       1.00      1.00      1.00        22
          32       1.00      1.00      1.00        24
          33       1.00      1.00      1.00        17
          34       1.00      1.00      1.00        28
          35       1.00      1.00      1.00        22
          36       1.00      1.00      1.00        25
          37       1.00      1.00      1.00        19
          38       1.00      1.00      1.00        26
          39       1.00      1.00      1.00        22
          40       1.00      1.00      1.00        34

    accuracy                           1.00       984
   macro avg       1.00      1.00      1.00       984
weighted avg       1.00      1.00      1.00       984

In [25]:
train_acc = model.score(X_train, y_train)

print(train_acc)

1.0

# Save Model

In [26]:
import joblib

joblib.dump(model, 'disease_model.pkl')
joblib.dump(le, 'label_encoder.pkl')
joblib.dump(all_symptoms, 'all_symptoms.pkl')

['all_symptoms.pkl']